Repository open-company/open-company-email, pull requests merged in 2018-12, with the labels that each got.

#32 Change digest footer to change digest settings.
  src/oc/email/content.clj
Labels: reviewing

#31 More email digest tweaks
  resources/css/oc.css
  src/oc/email/content.clj
  src/oc/email/mailer.clj
Labels: ready for deploy

#30 Storage lib
  project.clj
  resources/css/oc.css
  src/oc/email/config.clj
  src/oc/email/content.clj
  src/oc/email/mailer.clj
Labels: ready for deploy

#34 Always use post data to get the title/headline.
  src/oc/email/mailer.clj
Labels: ready for review

#35 Generate id token for url
  project.clj
  src/oc/email/content.clj
Labels: reviewing

#36 Post link behaviour
  project.clj
  src/oc/email/content.clj
Labels: reviewing
